Add quality templates from products into productions.
NaN-tic/trytond-production_quality_control pull request #1
Opened 2021-05-06 13:46 UTC by juanjo-nan

Add cron to create quality test in productions.
Fix views.
Dont end a production until all the quality test are successful.

043843

2021-05-14 14:44 UTC, raimonesteve commented on production.py
> +    quality_templates = fields.One2Many('product.template-quality.template', 'template', "Quality Templates")
Si canviem de m2o a o2m, que passa amb teb i altres entorns que tinguin aquest mòdul? hi ha script per "migrar" les dades?

2021-05-14 14:44 UTC, raimonesteve commented on production.py
> -    def on_change_product(self):
Es millor canviar el m2p per un function(o2m) i no relacionar-ho amb el on_change? No seria millor "desar" les plantilles actuals a la producció, en contres del function, ja que que cada cop que es canvi un plantilla en el producte, quedarà "canviat" a totes les produccions?

2021-05-14 14:44 UTC, raimonesteve commented on production.py
> +                if quality_template.company.id == context.get('company'):
En principi aquesta condició no caldria pq "product.template.quality_templates" t'hauria de retornar les de teva empresa en que estàs si es crea al regla d'accés. (a no ser que es vulgui ja preparar pel drop company rules)

2021-05-14 14:44 UTC, raimonesteve commented on production.py
> +            production.save()
Personalment m'agrada més un sol write en bloc.

```
cls.write(to_write)
```

2021-05-14 14:44 UTC, raimonesteve commented on production.py
> +                ('document', '=', 'production,%s' % str(production.id)),
Ja que defineixes la variable, es pot fer:

```
('document', '=', document),
```

2021-05-14 14:44 UTC, raimonesteve commented on production.py
> +                        production=production.number))
Sóc més partidari per obtenir el nom descriptiu, fer:

```
production.rec_name
```

2021-05-17 13:24 UTC, juanjo-nan commented on production.py
> +    quality_templates = fields.One2Many('product.template-quality.template', 'template', "Quality Templates")
És un mòdul que només està teb, si es fa el canvi ara, no afectarà cap altre client: [ho pots veure als components](https://nan.nan-tic.com:8000/#nan/model/project.work.component/339;name=%22Components%22&views=%5B459%2C460%5D)

2021-05-18 15:14 UTC, juanjo-nan commented on production.py
> +                if quality_template.company.id == context.get('company'):
Amb el canvi que es farà la 6.0 amb les companyies, es millor deixar-lo així.

2021-05-18 15:24 UTC, juanjo-nan commented on production.py
> +            production.save()
Ho he parlat amb l'Albert, al final seria millor fer un save massiu de totes les produccions afectades.
```

2021-05-18 15:24 UTC, juanjo-nan commented on production.py
> -    def on_change_product(self):
Ho he parlat amb l'Albert, en aquest cas s'ha decidit que és millor deixar-lo així.

2021-06-22 22:08 UTC, albertca requested changes

2021-06-22 22:08 UTC, albertca commented on production.py
> +            if len(tests_not_successful) != 0:
D'això n'hem de parlar perquè si no admetem controls de qualitat fallits, llavors no es podrà tancar mai la producció en qüestió i això dubto que sigui un comportament adequat.

2021-06-22 22:08 UTC, albertca commented on production.py
> +    template = fields.Many2One('product.template', "Template")
Falta required=True i ondelete='CASCADE'

2021-06-22 22:08 UTC, albertca commented on production.py
> +    quality_template = fields.Many2One('quality.template', "Quality Template")
Falta required=True

2021-06-22 22:08 UTC, albertca commented on production.py
> +    time_since_quality_control = fields.DateTime('Time since quality control')
Crec que l'hauríem de fer readonly

2021-07-19 13:59 UTC, albertca commented on production.py
> +                    production.save()
You should save all productions at once at the end of the loop:

cls.save(productions)

2021-07-27 07:51 UTC, merged